// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdDVhNOAiA91_ZrdlcD-NnyIsY2apYII',
    appId: '1:935386520809:web:472aa4cb23a73b6206e478',
    messagingSenderId: '935386520809',
    projectId: 'livechatdemo-e6692',
    authDomain: 'livechatdemo-e6692.firebaseapp.com',
    storageBucket: 'livechatdemo-e6692.appspot.com',
    measurementId: 'G-NFN4MN7S6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRyWDA6JuuiFEQXg_FZjDvCx8BNSVR3cY',
    appId: '1:935386520809:android:884e06b946cfe31706e478',
    messagingSenderId: '935386520809',
    projectId: 'livechatdemo-e6692',
    storageBucket: 'livechatdemo-e6692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQutth7pv3Qb0dC7x2eifReCB35uKNEME',
    appId: '1:935386520809:ios:489b2608e9b4c01806e478',
    messagingSenderId: '935386520809',
    projectId: 'livechatdemo-e6692',
    storageBucket: 'livechatdemo-e6692.appspot.com',
    iosClientId: '935386520809-af5gfnb7nd68ok67ur6qsf0pall4qd3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQutth7pv3Qb0dC7x2eifReCB35uKNEME',
    appId: '1:935386520809:ios:489b2608e9b4c01806e478',
    messagingSenderId: '935386520809',
    projectId: 'livechatdemo-e6692',
    storageBucket: 'livechatdemo-e6692.appspot.com',
    iosClientId: '935386520809-af5gfnb7nd68ok67ur6qsf0pall4qd3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveChat',
  );
}
